<a href="https://colab.research.google.com/github/rajnish80130/Real-state-Capstone-Project/blob/main/coordinates_scarraper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
import pandas as pd
import time

In [2]:
API_KEY = 'eabd44fdfb3143b9804eaa0cad692354'

In [3]:
def get_coordinates(sector):
    query = f"Sector {sector}, Gurgaon, India"
    url = f"https://api.opencagedata.com/geocode/v1/json?q={query}&key={API_KEY}"

    response = requests.get(url)
    data = response.json()

    if data['results']:
        geometry = data['results'][0]['geometry']
        return geometry['lat'], geometry['lng']
    return None, None

In [4]:
# DataFrame
sectors = list(range(1, 116))
data = []

In [5]:
for sector in sectors:
    lat, lng = get_coordinates(sector)
    data.append({'Sector': f'Sector {sector}', 'Latitude': lat, 'Longitude': lng})
    time.sleep(1)  # Respect rate limits

In [6]:
df = pd.DataFrame(data)

In [7]:
df.head()

     Sector   Latitude  Longitude
0  Sector 1  28.518781  77.041862
1  Sector 2  28.509050  77.034283
2  Sector 3  28.362766  76.919326
3  Sector 4  28.475006  77.010353
4  Sector 5  28.480392  77.019095

In [8]:
df.rename(columns={'Sector':'sector'}, inplace=True)

In [9]:
df.head()

     sector   Latitude  Longitude
0  Sector 1  28.518781  77.041862
1  Sector 2  28.509050  77.034283
2  Sector 3  28.362766  76.919326
3  Sector 4  28.475006  77.010353
4  Sector 5  28.480392  77.019095

In [10]:
df['sector'] = df['sector'].str.lower()

In [11]:
df.head()

     sector   Latitude  Longitude
0  sector 1  28.518781  77.041862
1  sector 2  28.509050  77.034283
2  sector 3  28.362766  76.919326
3  sector 4  28.475006  77.010353
4  sector 5  28.480392  77.019095

In [12]:
df.shape

(115, 3)

In [13]:
df.to_csv('gurgaon_sector_coordinates.csv', index=False)